// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opfnqkbssivwtkpzobyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wZm5xa2Jzc2l2d3RrcHpvYnlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4MTcyMDgsImV4cCI6MjA5MDM5MzIwOH0.W5YBD2ZWaXgeQg7LxMlFToDlpUT_va1I1alJke2o8bI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});